version: "3.9"
services:
  quake:
    environment:
      - DISPLAY=$DISPLAY
      - ALSA_CARD=Generic
    volumes:
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"
    devices:
      - /dev/snd
    container_name: quake-container
    image: quake-image
